apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: teddy2468/gestion-depenses-app:latest  # ou gestion-depenses-app:latest si local
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            value: mysql-service  
          - name: DB_NAME
            value: gestion_depenses_db
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password