# Generated by Django 5.1.7 on 2025-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='montant',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='montant',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Dépense sans titre', max_length=200),
        ),
        migrations.AddField(
            model_name='revenue',
            name='title',
            field=models.CharField(default='Revenue sans titre', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='Dépense sans description'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='description',
            field=models.TextField(blank=True, default='Revenue sans description'),
        ),
    ]
