# Generated by Django 5.1.7 on 2025-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_categorie_rename_montant_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='source',
        ),
        migrations.AddField(
            model_name='revenue',
            name='categorie',
            field=models.CharField(choices=[('Salaire', 'Salaire'), ('Prime', 'Prime'), ('Vente', 'Vente'), ('Cadeau', 'Cadeau'), ('Autres', 'Autres')], default='Autres', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categorie',
            field=models.CharField(choices=[('Logement', 'Logement'), ('Transport', 'Transport'), ('Nourriture', 'Nourriture'), ('Loisirs', 'Loisirs'), ('Santé', 'Santé'), ('Autres', 'Autres')], default='Autres', max_length=50),
        ),
    ]
